1. NumPy를 사용하여 다음과 같은 행렬을 만든다.
```
10 20 30 40
50 60 70 80
```

In [1]:
import numpy as np
import pandas as pd

In [2]:
np.array([[10,20,30,40],
         [50,60,70,80]])

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

2. 다음 행렬과 같은 행렬이 있다.
```
m = np.array([[ 0,  1,  2,  3,  4],
              [ 5,  6,  7,  8,  9],
              [10, 11, 12, 13, 14]])
이 행렬에서 값 7 을 인덱싱한다.
이 행렬에서 값 14 을 인덱싱한다.
이 행렬에서 배열 [6, 7] 을 슬라이싱한다.
이 행렬에서 배열 [7, 12] 을 슬라이싱한다.
이 행렬에서 배열 [[3, 4], [8, 9]] 을 슬라이싱한다.
```

In [3]:
m = np.array([[ 0,  1,  2,  3,  4],
           [ 5,  6,  7,  8,  9],
           [10, 11, 12, 13, 14]])

# 행렬에서 값 7 을 인덱싱한다.
m[1,2]

# 행렬에서 값 14 을 인덱싱한다
m[-1,-1]

# 행렬에서 배열 [6, 7] 을 슬라이싱한다.
m[1,1:3]

# 행렬에서 배열 [7, 12] 을 슬라이싱한다.
m[1:,2]

# 행렬에서 배열 [[3, 4], [8, 9]] 을 슬라이싱한다.
m[:2,-2:] # m[:2,3:]

array([[3, 4],
       [8, 9]])

3.다음 행렬과 같은 배열이 있다.
```
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10,
              11, 12, 13, 14, 15, 16, 17, 18, 19, 20])
이 배열에서 3의 배수를 찾아라.
이 배열에서 4로 나누면 1이 남는 수를 찾아라.
이 배열에서 3으로 나누면 나누어지고 4로 나누면 1이 남는 수를 찾아라.
```

In [4]:
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10,
              11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

# 배열에서 3의 배수를 찾아라
x[x%3==0]

# 배열에서 4로 나누면 1이 남는 수를 찾아라
x[x%4==1]

# 배열에서 3으로 나누면 나누어지고 4로 나누면 1이 남는 수를 찾아라
c1 = x%3==0 
c2 = x%4==1
x[c1 & c2]

array([9])

4. 타이타닉 데이터셋에서 Age , sibsp, parch, fare 컬럼에 대해 표준화 하시오.
```
누락값에 대해서는 Age열은 평균 나이로 대체,
sibsp는 최대값으로 대체
parch는 최소값으로 대체
fare는 평균 요금으로 대체
```

In [5]:
data = pd.read_csv('train.csv')
data.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [6]:
# 누락값에 대해서는 Age열은 평균 나이로 대체
data = data.fillna(np.mean(data.Age))

In [7]:
# sibsp는 최대값으로 대체
data = data.fillna(max(data.SibSp))

In [8]:
# parch는 최소값으로 대체
data = data.fillna(min(data.Parch))

In [9]:
# fare는 평균 요금으로 대체
data = data.fillna(np.mean(data.Fare))

### numpy

In [10]:
# Age , sibsp, parch, fare 컬럼에 대해 표준화하여 새로운 열에 추가
data['Age_z'] = (data.Age-np.mean(data.Age))/np.std(data.Age)

data['SibSp_z'] = (data.SibSp-np.mean(data.SibSp))/np.std(data.SibSp)

data['Parch_z'] = (data.Parch-np.mean(data.Parch))/np.std(data.Parch)

data['Fare_z'] = (data.Fare-np.mean(data.Fare))/np.std(data.Fare)

In [11]:
data.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare    Cabin Embarked     Age_z   SibSp_z  \
0      0         A/5 21171   7.2500  29.6991        S -0.592481  0.432793   
1      0          PC 17599  71.2833      C85        C  0.638789  0.432793   
2      0  STON/O2. 3101282   7.9250  29.6991        S -0.284663 -0.474545   
3      0            113803  53.1000     C123        S  0.407926  0.432793   
4      0            373450   8.0500  29.6991        S  0.407926 -0.474545   

    Parch_z    Fare_z  
0 -0.473674 -0.502445  
1 -0.473674  0.786845  
2 -0.473674 -0.488854  
3 -0.473674  0.420730  
4 -0.473674 -0.486337

In [12]:
# std
print(np.std(data.Age_z))
print(np.std(data.SibSp_z))
print(np.std(data.Parch_z))
print(np.std(data.Fare_z))

1.0000000000000007
1.0000000000000047
0.9999999999999845
1.0000000000000002


In [13]:
# var
print(np.var(data.Age_z))
print(np.var(data.SibSp_z))
print(np.var(data.Parch_z))
print(np.var(data.Fare_z))

1.0000000000000016
1.0000000000000095
0.9999999999999689
1.0000000000000004


### scipy.stats:zscore

In [14]:
import scipy.stats as ss

In [15]:
data['Age_z2'] = ss.zscore(data.Age)
data['SibSp_z2'] = ss.zscore(data.SibSp)
data['Parch_z2'] = ss.zscore(data.Parch)
data['Fare_z2'] = ss.zscore(data.Fare)

### sklearn.preprocessing

In [16]:
from sklearn.preprocessing import *

In [38]:
data['Age_z3'] = StandardScaler().fit_transform(np.array(data['Age']).reshape(-1,1))
data['SibSp_z3'] = StandardScaler().fit_transform(np.array(data['SibSp']).reshape(-1,1))
data['Parch_z3'] = StandardScaler().fit_transform(np.array(data['Parch']).reshape(-1,1))
data['Fare_z3'] = StandardScaler().fit_transform(np.array(data['Fare']).reshape(-1,1))

In [39]:
data.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare  ...   Parch_z    Fare_z    Age_z2  \
0      0         A/5 21171   7.2500  ... -0.473674 -0.502445 -0.592481   
1      0          PC 17599  71.2833  ... -0.473674  0.786845  0.638789   
2      0  STON/O2. 3101282   7.9250  ... -0.473674 -0.488854 -0.284663   
3      0            113803  53.1000  ... -0.473674  0.420730  0.407926   
4      0            373450   8.0500  ... -0.473674 -0.486337  0.407926   

   SibSp_z2  Parch_z2   Fare_z2    Age_z3  SibSp_z3  Parch_z3   Fare_z3  
0  0.432793 -0.473674 -0.502445 -0.592481  0.432793 -0.473674 -0.502445  
1  0.432793 -0.473674  0.786845  0.638789  0.432793 -0.473674  0.786845  
2 -0.474545 -0.473674 -0.488854 -0.284663 -0.474545 -0.473674 -0.488854  
3  0.432793 -0.473674  0.420730  0.407926  0.432793 -0.473674  0.420730  
4 -0.474545 -0.473674 -0.486337  0.407926 -0.474545 -0.473674 -0.486337  

[5 rows x 24 columns]