2020.01.06
### numpy, pandas

In [ ]:
# numpy(전처리). pandas(분석)
# matplotlib, seaborn 시각화

'''
전처리 : 결측치, 표준화, 정규화

정규화 : (각 속성값-최소값) / (각 속성의 최대값 - 최소값) => 0~1사이의 값으로
표준화 : 평균을 0으로 표준편차를 1로 (각 속성값-평균) / 표준편차
one-hot encoding : 메모리 낭비 심함 => 사이즈가 작은 것은 괜찮지만 큰건 비효율 => 밀집벡터
밀집벡터(워드2벡터)
'''

In [ ]:
'''
리스트 : 속도 느림, 메모리 많이 차지
배열(array) : 속도 빠름, 메모리 적게 차지

넘파이 배열과 리스트의 차이점
- 리스트: 모든 데이터저장 가능
- 배열: 모두 같은 자료형으로 통일해 주어야함, 원소개수 변경 못함
- 배열은 파이썬에서 제공하지 않음
- 파이썬 환경에서 넘파이 패키지를 활용하여 배열을 사용할 수 있음


넘파이 : 수치해서 패키지, 다차원 배열 구조 
        벡터, 행렬을 사용하는 선행대수 계산시 사용
        넘파이 배열 연산 빠름(벡터화 연산)'''

### Numpy
### array

In [1]:
# numpy 가져오기
import numpy

In [124]:
ar = numpy.array([0,1,2,3,4]) # 2차원:[[0,1,2,3,4]],  3차원:[[[0,1,2,3,4]]]
print(ar)
print(type(ar))

[0 1 2 3 4]
<class 'numpy.ndarray'>


In [ ]:
# 100*100 크기의 이미지(픽셀 : 1000개)
# 0~255사이의 gray scale
# => 몇 차원? 10000차원

In [126]:
# data에 저장된 모든 값들에 대해 2배
data = list(range(0,10))
new = []
for i in data:
    new.append(i*2)
print(new)

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]


In [125]:
# 시간 복잡도(CPU) : 연산결과가 나오기가지 수행되는 라인의 수
# 연산 횟수가 고정되어 잇을때 :O(1)
# 연산 횟숫가 100일때 : O(100)
    
# 공간 복잡도(MEM)

In [127]:
import numpy as np

data = list(range(0,10))
x = np.array(data)
print(x*2) # 벡터화 연산: for 문 사용 x
print(data*2) # list는 곱하면 리스트 안의 원소가 두배가 되는 것이 아니고 리스트 전체가 두번 반복

[ 0  2  4  6  8 10 12 14 16 18]
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [130]:
import numpy as np

a = np.array([1,2,3])
b = np.array([4,5,6])
a2 = [1,2,3]
b2 = [4,5,6]

print(2*a2+b2) # list
print(2*a+b) # array -> 요소간 연산 element wise~: 벡터화 연산

[1, 2, 3, 1, 2, 3, 4, 5, 6]
[ 6  9 12]


In [133]:
print(a2 ==2)
# 논리연산에서도 각 요소마다
print(a ==2)

False
[False  True False]


In [134]:
print(a > 2)

[False False  True]


### 2차원 배열 (행렬, matrix)

가로줄 : 행

세로줄 : 열

In [135]:
# 2차원 배열 : 리스트의 리스트
m = np.array([[0,1,2,],[3,4,5]]) 
# 열 : 안쪽 리스트 길이 => 열 3개
# 행 : 바깥쪽 리스트 길이 => 행 2개
# 0 1 2
# 3 4 5

In [136]:
# 행의 개수
print(len(m))
# 열의 개수
print(len(m[0]))

2
3


### 3차원 배열

In [38]:
m = np.array([[[1,2,3,4],
          [5,6,7,8],
          [9,10,11,12]],
         [[1,2,3,4],
          [5,6,7,8],
          [9,10,11,12]]])

# 2행 3열 4깊이
len(m)
len(m[0])
len(m[0][0])

print(m.ndim)
print(m.shape)

3
(2, 3, 4)


### ndim, shape

In [40]:
# 차원이 높아지면 저렇게 적기 힘듬 =>
a = np.array([4,5,6])
print(a.ndim) # 배열의 차원
print(a.shape) # 배열의 크기

1
(3,)


In [39]:
a = np.array([[0,1,2],[4,5,6]])
print(a.ndim)
print(a.shape)

2
(2, 3)


In [59]:
# 문제1
# 연속으로 숫자 3개를 곱했을때 얻어진 결과값이 가장 큰 구간이 어디인지
a = [3,2,1,-4,-7,-9,8,-5,3,-1]

res = 0
c = a[0]*a[1]*a[2]
for i in range(len(a)-2):
    if a[i]*a[i+1]*a[i+2] > c:
        c = a[i]*a[i+1]*a[i+2]
        res = i
print(res)
print(a[res],a[res+1],a[res+2])

4
-7 -9 8


In [76]:
# 문제2
# 숫자 2*2의 영역을 구성하는 수를 곱했을때 얻어진 결과값이 가장 큰구간이 어디인지 출력
a = np.array([[3,1,-2],[2,1,-3],[-2,0,-7]])

# 처음 4개의 곱의 값을 주고 이 값보다 큰 값이 나오면 그 값을 저장
c = a[0][0]*a[0][1]*a[1][0]*a[1][1]
res_i=0
res_j=0
for i in range(a.shape[0]-1):
    for j in range(a.shape[1]-1):        
        if a[i][j]*a[i][j+1]*a[i+1][j]*a[i+1][j+1] > c:
            c = a[i][j]*a[i][j+1]*a[i+1][j]*a[i+1][j+1]
            res_i = i
            res_j = j
            
print(a[res_i][res_j],a[res_i][res_j+1])
print(a[res_i+1][res_j],a[res_i+1][res_j+1])

3 1
2 1


#### slicing

In [137]:
# array slicing
ar = np.array([[1,2,3,4],[5,6,7,8,]])
# ar[행,열]
ar[0,:] # 첫번째 행 전체
ar[:,1] # 전체 행에서 2번째 열
ar[:,:2] # [1, 2],[5, 6]]

array([[1, 2],
       [5, 6]])

#### indexing

In [138]:
# indexing : 데이터 1개를 참조
ar = np.array([0,1,2])
ar[-1] # 2

ar = np.array([[1,2,3,4],[5,6,7,8,]])
ar[-1][-1] # 8
ar[0][0] # 1
ar[0,0] # 1, 다차원 배열에서는 컴마로 접근
ar[1,1] # 6

6

#### 불린 참조

In [91]:
# 불린 참조 : 조건에 대해 만족하는 값을 추출
ar = np.array([2,3,4,5])
bidx = np.array([True,True,False,True])
ar[bidx]

array([2, 3, 5])

In [92]:
ar != 4

array([ True,  True, False,  True])

In [93]:
ar[ar != 4]

array([2, 3, 5])

In [94]:
ar[ar%2==0]

array([2, 4])

In [95]:
ar[ar >3]

array([4, 5])

In [139]:
ar = np.array([2,3,4,5])
idx = np.array([0,3])
print(ar[idx])

idx = np.array([0,0,1,1])
print(ar[idx])

[2 5]
[2 2 3 3]


In [106]:
ar = np.array([[1,2,3,4],[5,6,7,8]])
print(ar[:,(0,3)])

# 다른 방법
# ar[:,[0,3]]

# ar[:,[True,False,False,True]]

# dix = np.array([0,3])
# ar[:,dix]

[[1 4]
 [5 8]]


In [112]:
ar = np.array([[1,2,3,4],[5,6,7,8],[9,0,11,12],[13,14,15,16]])

ar[[2,0,-1],:] # 원소 순 2- > 0 -> -1
# ar[:]  ar전체 행
# ar  ar 배열 전체
# ar[:,:]  전체 행 전체 열

array([[ 9,  0, 11, 12],
       [ 1,  2,  3,  4],
       [13, 14, 15, 16]])

### Pandas

In [ ]:
# 원데이터 : csv, tsv, txt, xls, xlsx, json,........ 
# Pandas :  원데이터를 데이터프레임으로 읽어서 분석(엑셀 시트)
# Numpy : 웬데이터를 다차원배열으로 읽어서 처리

In [ ]:
# 판다스 자료
# https://pandas.pydata.org/ 우측 Release 박스에 pdf누르면 다운로드

In [140]:
import pandas as pd

csvTest = pd.read_csv("test_csv.csv")
type(csvTest)

pandas.core.frame.DataFrame

In [141]:
csvTest

ID LAST_NAME  AGE
0   1       KIM   25
1   2       LEE   22
2   3      PARK   33
3   4      CHOI   24
4   5       CHO   30

In [142]:
csvTest.shape

(5, 3)

In [143]:
pd.read_csv("test_text.txt") # csv파일뿐만 아니라 다른 파일도 읽을 수 있담
# csv는 자동으로 ,기준으로 구분

ID|LAST_NAME|AGE
0         1|KIM|25
1         2|LEE|22
2        3|PARK|33
3        4|CHOI|24
4         5|CHO|30

In [144]:
pd.read_csv("test_text.txt",sep='|')

ID LAST_NAME  AGE
0   1       KIM   25
1   2       LEE   22
2   3      PARK   33
3   4      CHOI   24
4   5       CHO   30