2020.01.06 연습문제

In [ ]:
# 문제1
# 연속으로 숫자 3개를 곱했을때 얻어진 결과값이 가장 큰 구간이 어디인지
a = [3,2,1,-4,-7,-9,8,-5,3,-1]

res = 0
c = a[0]*a[1]*a[2]
for i in range(len(a)-2):
    if a[i]*a[i+1]*a[i+2] > c:
        c = a[i]*a[i+1]*a[i+2]
        res = i
print(res)
print(a[res],a[res+1],a[res+2])

In [ ]:
# 문제2
# 숫자 2*2의 영역을 구성하는 수를 곱했을때 얻어진 결과값이 가장 큰구간이 어디인지 출력
a = np.array([[3,1,-2],[2,1,-3],[-2,0,-7]])

# 처음 4개의 곱의 값을 주고 이 값보다 큰 값이 나오면 그 값을 저장
c = a[0][0]*a[0][1]*a[1][0]*a[1][1]
res_i=0
res_j=0
for i in range(a.shape[0]-1):
    for j in range(a.shape[1]-1):        
        if a[i][j]*a[i][j+1]*a[i+1][j]*a[i+1][j+1] > c:
            c = a[i][j]*a[i][j+1]*a[i+1][j]*a[i+1][j+1]
            res_i = i
            res_j = j
            
print(a[res_i][res_j],a[res_i][res_j+1])
print(a[res_i+1][res_j],a[res_i+1][res_j+1])

### 문제3

m = np.array([[ 0,  1,  2,  3,  4],
              [ 5,  6,  7,  8,  9],
              [10, 11, 12, 13, 14]])
이 행렬에서 값 7 을 인덱싱한다.
이 행렬에서 값 14 을 인덱싱한다.
이 행렬에서 배열 [6, 7] 을 슬라이싱한다.
이 행렬에서 배열 [7, 12] 을 슬라이싱한다.
이 행렬에서 배열 [[3, 4], [8, 9]] 을 슬라이싱한다.

In [16]:
import numpy as np

m = np.array([[ 0,  1,  2,  3,  4],
              [ 5,  6,  7,  8,  9],
              [10, 11, 12, 13, 14]])
#1
print(m[1, 2])
#2
print(m[-1, -1])
#3
print(m[1, 1:3])
#4
print(m[1:, 2])
#5
print(m[:2, 3:])

7
14
[6 7]
[ 7 12]
[[3 4]
 [8 9]]


### 문제 4

x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10,
              11, 12, 13, 14, 15, 16, 17, 18, 19, 20])
이 배열에서 3의 배수를 찾아라.
이 배열에서 4로 나누면 1이 남는 수를 찾아라.
이 배열에서 3으로 나누면 나누어지고 4로 나누면 1이 남는 수를 찾아라.

In [100]:
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10,
              11, 12, 13, 14, 15, 16, 17, 18, 19, 20])
#1
print(x[x%3 == 0])
#2
print(x[x%4 ==1])
#3
a = x[x%3==0]
b = a[a%4 ==1]
print(b)

[ 3  6  9 12 15 18]
[ 1  5  9 13 17]


array([9])

### 문제3

In [ ]:
상자들이 쌓여있는 방이 있다
방이 오른쪽으로 90도 회전하여 상자들이 중력의 영향을 받아 낙하한다고 할 때, 낙차가 가장 큰 상자를 구하여 그 낙차를 리턴하는 프로그램을 작성하시오.
중력은 회전이 완료된 후 적용된다
상자들은 모두 한쪽 벽면에 붙여진 상태로 쌓여 2차원의 형태를 이루며 벽에서 떨어져서 쌓인 상자는 없다
가로길이는 항상 100이며 세로길이도 항상100이다
즉 상자는 최소 0 최대 100높이로 쌓을 수 있다

In [ ]:
# 각 열의 상자개수  입력받기
a = input()

# 100x100 matrix 생성
h = 100
v = 100
room = np.array([[0]*h]*v)

# 입력 받은 상자 개수대로 상자 위치 표시(상자가 있으면 1, 없으면 0)
for i in range(h):
    j = 0
    for k in range(int(a[i])):
        room[-(j+1),i] = 1
        j += 1
# 룸
print(room)
print('-'*20)

# 회전
new_room=[]
for i in range(room.shape[1]):
    new = []
    for j in range(room.shape[0]):
        new.append(room[-(j+1)][i])
    new_room.append(new)
new_room = np.array(new_room)

# 회전된 룸
print(new_room)    

# 최대 낙차 구하기
c = 0
for i in range(new_room.shape[1]):
    for j in range(new_room.shape[0]):
        # new_room[j,i] 밑에 있는 0의 개수가 상자가 낙차할 거리 => new_room[j,i]이 1일때 그 위치 이하의 0의 개수 체크
        if new_room[j,i] ==1 and list(new_room[j:,i]).count(0) > c:
            c = list(new_room[j:,i]).count(0)
            location=[j,i]
            
print(c)
print(location)

In [105]:
############################### 회전 해주지 않고 구하기 ##############################
# 각 열의 상자개수  입력받기
a = input() #74200607

# 100x100 matrix 생성 대신 8x9
h = 8
v = 9
room = np.array([[0]*h]*v)

# 입력 받은 상자 개수대로 상자 위치 표시(상자가 있으면 1, 없으면 0)
for i in range(h):
    j = 0
    for k in range(int(a[i])):
        room[-(j+1),i] = 1
        j += 1
# 룸
print(room)
print('-'*20)

#낙차 값구하기
c = 0
for i in range(v):
    for j in range(h):
        # 0의 개수가 상자가 낙차할 거리 => room[j,i]이 1일때 그 위치 오른쪽의 0의 개수 체크
        # 0의 개수가 저장되어 있는 0의 개수보다 크면 그값과 그 위치 저장
        # 위치는 회전된 위치로 저장
        if room[i,j] == 1 and list(room[i,j:]).count(0) > c:
            c = list(room[i,j:]).count(0)
            location = [j,room.shape[0]-(i+1)]
print(c)
print(location)

74200607
[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 1]
 [1 0 0 0 0 1 0 1]
 [1 0 0 0 0 1 0 1]
 [1 1 0 0 0 1 0 1]
 [1 1 0 0 0 1 0 1]
 [1 1 1 0 0 1 0 1]
 [1 1 1 0 0 1 0 1]]
--------------------
6
[0, 6]
