In [ ]:
# https://numpy.org/doc/ 
넘파이 자료

In [1]:
import pandas as pd
import numpy as np

In [3]:
pd.read_csv('test_text.txt')

ID|LAST_NAME|AGE
0         1|KIM|25
1         2|LEE|22
2        3|PARK|33
3        4|CHOI|24
4         5|CHO|30

In [4]:
# sep을 사용하여 분리
pd.read_csv('test_text.txt',sep="|")

ID LAST_NAME  AGE
0   1       KIM   25
1   2       LEE   22
2   3      PARK   33
3   4      CHOI   24
4   5       CHO   30

### 행 인덱스 설정 index_col

In [5]:
# 디폴트 행 인덱스 : 0번
# index_col로 행 인텍스 설정 가능
pd.read_csv('test_text.txt', sep = "|", index_col = 'ID') # ID를 인덱스로

LAST_NAME  AGE
ID               
1        KIM   25
2        LEE   22
3       PARK   33
4       CHOI   24
5        CHO   30

In [6]:
pd.read_csv('test_text.txt', sep = "|", index_col = 0) # 0번을 인덱스로

LAST_NAME  AGE
ID               
1        KIM   25
2        LEE   22
3       PARK   33
4       CHOI   24
5        CHO   30

### header 열 이름

In [7]:
# header = 있음으로 디폴트 설정되어 있음
pd.read_csv('test_text_without_name.txt', sep = "|", index_col = 0)

KIM  25
1          
2   LEE  22
3  PARK  33
4  CHOI  24
5   CHO  30

In [8]:
# read_CSV()에서 ()안에 적어 줄때 순서를 정해주지 않는다면 첫번째 인자로 무조건 파일로
# header가 없으면 None라고 지정해주어 데이터가 header로 가는 것을 방지
pd.read_csv('test_text_without_name.txt', header = None, sep = "|", index_col = 0)

1   2
0          
1   KIM  25
2   LEE  22
3  PARK  33
4  CHOI  24
5   CHO  30

### skiprows 건너띄고 싶은 데이터가 있을때 

In [9]:
pd.read_csv('test_text.txt',sep="|",skiprows = 1) # 연속적으로 여러 줄 건너뛸 경우, 첫번째(0번) 줄을 띄어 넘으니깐 그다음 줄이 header로
pd.read_csv('test_text.txt',sep="|",skiprows = [1,3]) # 비연속적으로 여러줄을 건너뛸경우, 1번,3번줄 뛰어넘는다

ID LAST_NAME  AGE
0   2       LEE   22
1   4      CHOI   24
2   5       CHO   30

### nrows 위에서 부터 불러오고 싶은 개수 만큼 불러오기

In [10]:
pd.read_csv('test_text.txt',sep="|", nrows = 3) # 0~3줄만 불러오기

ID LAST_NAME  AGE
0   1       KIM   25
1   2       LEE   22
2   3      PARK   33

### info() DataFrame의 정보를 알고 싶을때

In [17]:
data = pd.read_csv('test_text.txt',sep="|", nrows = 3)
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
ID           3 non-null int64
LAST_NAME    3 non-null object
AGE          3 non-null int64
dtypes: int64(2), object(1)
memory usage: 200.0+ bytes


### na_values 결측값을 지정해주면 NaN으로 바꾸어줌

In [19]:
# 결측값 : 없음, 모름
# AGE가 object인 이유 : 숫자가 있다가 문자가 한개라도 있으면 object
pd.read_csv("test_text_NA.txt",sep="|").info()
pd.read_csv("test_text_NA.txt",sep="|")

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
ID           5 non-null int64
LAST_NAME    5 non-null object
AGE          5 non-null object
dtypes: int64(1), object(2)
memory usage: 248.0+ bytes


ID LAST_NAME AGE
0   1       KIM  25
1   2       LEE  없음
2   3      PARK  33
3   4        모름  24
4   5       CHO  30

In [38]:
pd.read_csv("test_text_NA.txt",sep="|").info() # 숫자가 있다가 문자가 한개라도 있으면 object

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
ID           5 non-null int64
LAST_NAME    5 non-null object
AGE          5 non-null object
dtypes: int64(1), object(2)
memory usage: 248.0+ bytes


na_values

In [37]:
pd.read_csv("test_text_NA.txt",sep="|",na_values=['없음','모름']) # 숫자가 있다가 문자가 한개라도 있으면 object

ID LAST_NAME   AGE
0   1       KIM  25.0
1   2       LEE   NaN
2   3      PARK  33.0
3   4       NaN  24.0
4   5       CHO  30.0

In [39]:
pd.read_csv("test_text_NA.txt",sep="|",na_values=['없음','모름']).info() # age가 int -> flost가 됨

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
ID           5 non-null int64
LAST_NAME    4 non-null object
AGE          4 non-null float64
dtypes: float64(1), int64(1), object(1)
memory usage: 248.0+ bytes


데이터 타입 지정하기

In [41]:
# 데이터 타입 지정 : dict 형식으로
data = pd.read_csv('test_text.txt',sep="|",
                  dtype = {'ID' : int,
                          'LAST_NAME' : str,
                          'AGE': str})
data.info()
data

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
ID           5 non-null int32
LAST_NAME    5 non-null object
AGE          5 non-null object
dtypes: int32(1), object(2)
memory usage: 228.0+ bytes


ID LAST_NAME AGE
0   1       KIM  25
1   2       LEE  22
2   3      PARK  33
3   4      CHOI  24
4   5       CHO  30

데이터를 파일로 저장 : to_csv

In [ ]:
# to_csv함수 : 데이터프레임을 csv로 저장
# DataFrame이라는 class 가 pandas에 들어있음
# DataFrame.to_csv() 에러 => pd.DataFrame()
#                         => from pandas import *(pandas의 모든 것을 가져온다) 후 DataFrame()
#                             => 다 가져오면 메모리낭비 => from pandas import DataFrame

In [45]:
from pandas import DataFrame

# 딕셔너리 데이터로 테이터프레임 생성하기

df = DataFrame({
    'id':['a1','a2','a3','a4','a5'],
    'x1':[1,2,3,4,5],
    'x2':[1.1,2.2,3.3,4.4,5.5]
})

print(df)

   id  x1   x2
0  a1   1  1.1
1  a2   2  2.2
2  a3   3  3.3
3  a4   4  4.4
4  a5   5  5.5


In [49]:
df = DataFrame({
    'id':['a1','a2','a3','a4','a5'],
    'x1':[1,2,3,4,5],
    'x2':[1.1,2.2,3.3,4.4,5.5]
},index=['a','b','c','d','e']) # 인수 2개  dict와 index, DataFrame(data={}) 가능

print(df)

   id  x1   x2
a  a1   1  1.1
b  a2   2  2.2
c  a3   3  3.3
d  a4   4  4.4
e  a5   5  5.5


In [52]:
df = DataFrame(data={
    'id':['a1','a2','a3','a4','a5'],
    'x1':[1,2,3,4,5],
    'x2':[1.1,2.2,3.3,4.4,5.5]
},index=['a','b','c','d','e'])
print(df)

# 결측값으로 구성된 새로운 행 추가
df2 = df.reindex(['a','b','c','d','e','f'])
print(df2)

df.reindex(['a','c','e','f'])
df.reindex(['a','k','c','e','f'])

   id  x1   x2
a  a1   1  1.1
b  a2   2  2.2
c  a3   3  3.3
d  a4   4  4.4
e  a5   5  5.5
    id   x1   x2
a   a1  1.0  1.1
b   a2  2.0  2.2
c   a3  3.0  3.3
d   a4  4.0  4.4
e   a5  5.0  5.5
f  NaN  NaN  NaN


id   x1   x2
a   a1  1.0  1.1
k  NaN  NaN  NaN
c   a3  3.0  3.3
e   a5  5.0  5.5
f  NaN  NaN  NaN

numpy

In [54]:
np.arange(8).shape

(8,)

In [55]:
np.arange(8).reshape(2,4)

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [56]:
np.arange(8).reshape(2,2,2)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [59]:
pd.DataFrame(np.arange(8).reshape(4,2))
# from pandas import DataFrame
# df(data=np.arange(8).reshape(4,2))

0  1
0  0  1
1  2  3
2  4  5
3  6  7

In [62]:
pd.DataFrame(np.arange(8).reshape(4,2),
            columns=['col0','col1'],
            index=['row0','row1','row2','row3'])

col0  col1
row0     0     1
row1     2     3
row2     4     5
row3     6     7

In [63]:
df1 = pd.DataFrame(np.arange(8).reshape(4,2),
            columns=['col0','col1'],
            index=['row0','row1','row2','row3'])
type(df1)

pandas.core.frame.DataFrame

transpose matrix

In [65]:
df1.T

row0  row1  row2  row3
col0     0     2     4     6
col1     1     3     5     7

In [66]:
df1

col0  col1
row0     0     1
row1     2     3
row2     4     5
row3     6     7

In [67]:
# axis(축,단수), axes(복수)
df1.axes # 행과 열의 모든 이름이 나옴

[Index(['row0', 'row1', 'row2', 'row3'], dtype='object'),
 Index(['col0', 'col1'], dtype='object')]

In [69]:
df1.dtypes

col0    int32
col1    int32
dtype: object

In [68]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4 entries, row0 to row3
Data columns (total 2 columns):
col0    4 non-null int32
col1    4 non-null int32
dtypes: int32(2)
memory usage: 224.0+ bytes


In [70]:
df1.shape

(4, 2)

In [71]:
df1.size #4*2 = 8

8

In [72]:
df1.values

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [74]:
np.random.randn(5) # randn = random + normal 평균 0 표준편차 1인 난수 발생

array([-0.32530591, -0.47056069,  1.47158373,  0.75779953, -1.74092938])

In [79]:
df = DataFrame({"cls_1":['a','a','b','b','c'],
         'v1':np.arange(5),
         'v2':np.random.randn(5)},
          index=['r0','r1','r2','r3','r4'])

In [80]:
df.index

Index(['r0', 'r1', 'r2', 'r3', 'r4'], dtype='object')

In [81]:
df.ix

C:\Users\student\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#ix-indexer-is-deprecated
  """Entry point for launching an IPython kernel.


In [82]:
df

cls_1  v1        v2
r0     a   0 -0.681100
r1     a   1  1.096987
r2     b   2 -0.737895
r3     b   3  0.393631
r4     c   4 -0.077276

In [83]:
df.ix[2] # 행 위치 ix는 0부터 시작

C:\Users\student\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#ix-indexer-is-deprecated
  """Entry point for launching an IPython kernel.


cls_1           b
v1              2
v2      -0.737895
Name: r2, dtype: object

In [84]:
df.ix['r2'] # 행이름을 줘도 됨

C:\Users\student\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#ix-indexer-is-deprecated
  """Entry point for launching an IPython kernel.


cls_1           b
v1              2
v2      -0.737895
Name: r2, dtype: object

In [85]:
# ix는 행 단위 indexing할때
# 행위치(정수)와 행 인텍스 이름을 모두 사용할 수 있다

# 인덱스 3번부터 마지막까지 추출
df.ix[3:]

C:\Users\student\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: FutureWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#ix-indexer-is-deprecated
  """


cls_1  v1        v2
r3     b   3  0.393631
r4     c   4 -0.077276

In [86]:
# warning없애기
import warnings
warnings.filterwarnings(action='ignore')

In [87]:
df.ix['r3':]

cls_1  v1        v2
r3     b   3  0.393631
r4     c   4 -0.077276

In [89]:
# 하위 몇개 상위 몇개 뽑기
df.head(3) # 상위 3개
df.tail(3) # 하위 3개

cls_1  v1        v2
r2     b   2 -0.737895
r3     b   3  0.393631
r4     c   4 -0.077276

In [90]:
# 특정 열만 보고싶을 때
df['cls_1']

r0    a
r1    a
r2    b
r3    b
r4    c
Name: cls_1, dtype: object

In [91]:
df.cls_1

r0    a
r1    a
r2    b
r3    b
r4    c
Name: cls_1, dtype: object

In [95]:
# 2개 이상 열을 참조할 때
df[['cls_1','v1']]

cls_1  v1
r0     a   0
r1     a   1
r2     b   2
r3     b   3
r4     c   4

In [97]:
print(type(df[['cls_1']])) # DataFrame
print(type(df['cls_1'])) # Series

<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.series.Series'>


In [98]:
df = DataFrame({"cls_1":['a','a','b','b','c'],
         'v1':np.arange(5),
         'v2':np.random.randn(5)},
          index=['r0','r1','r2','r3','r4'])
df

cls_1  v1        v2
r0     a   0  0.180357
r1     a   1  0.617168
r2     b   2 -0.166802
r3     b   3  0.597858
r4     c   4  1.204811

In [102]:
# 행인덱스 : r3,r4 제거 r5,r6 추가
df.reindex(['r0','r1','r2','r5','r6'])

cls_1   v1        v2
r0     a  0.0  0.180357
r1     a  1.0  0.617168
r2     b  2.0 -0.166802
r5   NaN  NaN       NaN
r6   NaN  NaN       NaN

In [107]:
# 없는 값에 지정 데이터 넣기
df.reindex(['r0','r1','r2','r3','r4','r5','r6'],fill_value=0)
df.reindex(['r0','r1','r2','r3','r4','r5','r6'],fill_value='missing')
df.reindex(['r0','r1','r2','r3','r4','r5','r6'],fill_value='NA')

cls_1  v1        v2
r0     a   0  0.180357
r1     a   1  0.617168
r2     b   2 -0.166802
r3     b   3  0.597858
r4     c   4   1.20481
r5    NA  NA        NA
r6    NA  NA        NA

시계열 데이터

date_range : 

In [110]:
# 시계열 데이터 : DataFrame에서 index를 만들때 date_range함수 사용
pd.date_range("1/7/2020",periods=5) # datetime : 날짜데이트 타입

DatetimeIndex(['2020-01-07', '2020-01-08', '2020-01-09', '2020-01-10',
               '2020-01-11'],
              dtype='datetime64[ns]', freq='D')

In [113]:
pd.date_range("1/7/2020",periods=5, freq ='M')

DatetimeIndex(['2020-01-31', '2020-02-29', '2020-03-31', '2020-04-30',
               '2020-05-31'],
              dtype='datetime64[ns]', freq='M')

In [116]:
pd.date_range("1/7/2020",periods=5,freq="Y")

DatetimeIndex(['2020-12-31', '2021-12-31', '2022-12-31', '2023-12-31',
               '2024-12-31'],
              dtype='datetime64[ns]', freq='A-DEC')

In [115]:
pd.date_range("1/7/2020",periods=5, freq="H")

DatetimeIndex(['2020-01-07 00:00:00', '2020-01-07 01:00:00',
               '2020-01-07 02:00:00', '2020-01-07 03:00:00',
               '2020-01-07 04:00:00'],
              dtype='datetime64[ns]', freq='H')

In [120]:
date_idx = pd.date_range("1/7/2020",periods=5,freq="D")

df2 = pd.DataFrame({"c1":[5,3,7,6,4]})
df2

c1
0   5
1   3
2   7
3   6
4   4

In [121]:
df2 = pd.DataFrame({"c1":[5,3,7,6,4]}, index = date_idx)
df2

c1
2020-01-07   5
2020-01-08   3
2020-01-09   7
2020-01-10   6
2020-01-11   4

In [123]:
date_idx2 = pd.date_range('1/1/2020',periods=20,freq='D')

In [128]:
# df3 = pd.DataFrame({"c1":[5,3,7,6,4]},index = date_idx2)  에러 => shape이 맞지 않음. 실제는 5개 있는데 인덱스는 20개라서
# df3

df2.reindex(date_idx2) # NaN에 지정한 것을 채우고 싶을때 fill_value=0

c1
2020-01-01  NaN
2020-01-02  NaN
2020-01-03  NaN
2020-01-04  NaN
2020-01-05  NaN
2020-01-06  NaN
2020-01-07  5.0
2020-01-08  3.0
2020-01-09  7.0
2020-01-10  6.0
2020-01-11  4.0
2020-01-12  NaN
2020-01-13  NaN
2020-01-14  NaN
2020-01-15  NaN
2020-01-16  NaN
2020-01-17  NaN
2020-01-18  NaN
2020-01-19  NaN
2020-01-20  NaN

In [130]:
df2.reindex(date_idx2, method = 'ffill') # 전날 데이터가 복사되어 들어감 위에서부터 아래로 내려가면서 데이터가 들어감

c1
2020-01-01  NaN
2020-01-02  NaN
2020-01-03  NaN
2020-01-04  NaN
2020-01-05  NaN
2020-01-06  NaN
2020-01-07  5.0
2020-01-08  3.0
2020-01-09  7.0
2020-01-10  6.0
2020-01-11  4.0
2020-01-12  4.0
2020-01-13  4.0
2020-01-14  4.0
2020-01-15  4.0
2020-01-16  4.0
2020-01-17  4.0
2020-01-18  4.0
2020-01-19  4.0
2020-01-20  4.0

In [131]:
df2.reindex(date_idx2, method = 'bfill') #아래에서 위로 올라가면서 데이터가 채워짐

c1
2020-01-01  5.0
2020-01-02  5.0
2020-01-03  5.0
2020-01-04  5.0
2020-01-05  5.0
2020-01-06  5.0
2020-01-07  5.0
2020-01-08  3.0
2020-01-09  7.0
2020-01-10  6.0
2020-01-11  4.0
2020-01-12  NaN
2020-01-13  NaN
2020-01-14  NaN
2020-01-15  NaN
2020-01-16  NaN
2020-01-17  NaN
2020-01-18  NaN
2020-01-19  NaN
2020-01-20  NaN

In [ ]:
# https://archive.ics.uci.edu/ml/datasets.php
캘리포니아 대학 인공지능 연구실에서 오픈한 데이터 set
